// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://www.dbcook.com',
  serverKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
